<!DOCTYPE html>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<html lang="en">

<body>
<h1>${message}</h1>

<spring:url value="/test.txt" htmlEscape="true" var="springUrl" />
<c:url value="/static/test.txt" var="cUrl" />

<h2>Time: ${time}</h2>
<h2>Message: ${message}</h2>
<ul>
  <li><a href="${springUrl}">URL generated by Spring</a></li>
  <li><a href="${cUrl}">URL generated by JSTL</a></li>
  <li><a href="<c:url value="/fail"/>">This url always fail</a></li>
</ul>
</body>

</html>
